In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install transformers torch sentencepiece

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [6]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.42)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.4.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.10.0+cu128)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 17.0 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.4

In [2]:
model_path = "/content/drive/MyDrive/ML_Project/indobert-shopee-sentiment-model"

In [ ]:
import os

# Cek apakah folder tersebut benar-benar bisa diakses
path_uji = "/content/drive/MyDrive/ML_Project/indobert-shopee-sentiment-model"

if os.path.exists(path_uji):
    print("✅ Folder ditemukan!")
    print("Isi folder:", os.listdir(path_uji))
else:
    print("❌ Folder TIDAK ditemukan. Cek lagi penulisan path-nya.")

✅ Folder ditemukan!
Isi folder: ['config.json', 'model.safetensors', 'tokenizer_config.json', 'tokenizer.json']

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [4]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# 1. Tentukan device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Menggunakan device: {device}")

# 2. Load model (Pastikan path benar dan drive sudah mount)
model_path = "/content/drive/MyDrive/ML_Project/indobert-shopee-sentiment-model"

try:
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForSequenceClassification.from_pretrained(model_path)

    # 3. Pindahkan ke device HANYA jika model berhasil di-load
    model.to(device)
    model.eval() # Set ke mode evaluasi
    print("✅ Model berhasil dimuat ke device!")

except Exception as e:
    print(f"❌ Gagal memuat model: {e}")

Menggunakan device: cuda

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

✅ Model berhasil dimuat ke device!

In [7]:
from bertopic import BERTopic
import pandas as pd

path = '/content/drive/My Drive/CSV/shopee_reviews_cleaned.csv'
df = pd.read_csv(path)

# 3. Inisialisasi BERTopic (bahasa Indonesia)
topic_model = BERTopic(language="indonesian", calculate_probabilities=True, verbose=True)

# 4. Fit Model ke teks review
topics, probs = topic_model.fit_transform(df['content_cleaned'].astype(str))

# 5. Lihat Topik yang Terbentuk
topic_info = topic_model.get_topic_info()
print(topic_info.head(10))

# 6. Visualisasikan (Ini sangat keren untuk ditaruh di portofolio!)
topic_model.visualize_topics()

2026-05-11 07:10:47,566 - BERTopic - Embedding - Transforming documents to embeddings.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/30 [00:00<?, ?it/s]

2026-05-11 07:11:07,346 - BERTopic - Embedding - Completed ✓
2026-05-11 07:11:07,349 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-11 07:11:20,598 - BERTopic - Dimensionality - Completed ✓
2026-05-11 07:11:20,599 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-11 07:11:20,674 - BERTopic - Cluster - Completed ✓
2026-05-11 07:11:20,685 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-11 07:11:20,731 - BERTopic - Representation - Completed ✓

   Topic  Count                             Name  \
0     -1    113       -1_aplikasi_di_saya_shopee
1      0    163       0_shopee_belanja_dan_mudah
2      1    159       1_di_pengiriman_tidak_saya
3      2     72        2_iklan_aplikasi_di_video
4      3     54               3_ga_lama_sampe_di
5      4     51  4_aplikasi_bagus_belanja_sangat
6      5     38     5_mantap_keluar_bgusssss_lee
7      6     37   6_bagus_sangat_bermanfaat_baik
8      7     33                7_bgus_nan_mb_bgt
9      8     28               8_ok_oke_okey_wort

                                      Representation  \
0  [aplikasi, di, saya, shopee, ini, indonesia, t...
1  [shopee, belanja, dan, mudah, harga, banyak, s...
2  [di, pengiriman, tidak, saya, kurir, paket, ud...
3  [iklan, aplikasi, di, video, ganggu, saya, lai...
4  [ga, lama, sampe, di, krn, nya, bisa, udh, jel...
5  [aplikasi, bagus, belanja, sangat, membantu, y...
6  [mantap, keluar, bgusssss, lee, iku, lanjutkan...
7  [bagus, sangat, bermanfaat, baik, biasa, bergu...
8  [bgus, nan, mb, bgt, lemot, baguus, hapesaya, ...
9  [ok, oke, okey, wort, okeh, lanjutt, bgt, mant...

                                 Representative_Docs
0  [online mall terbaik aqohhh sementara ini buat...
1  [puas belanja di shopee, shopee belanja lebih ...
2  [untuk shopeenya udah bagus menurutku tapi unt...
3  [iklan lu tuh ganggu anjing udah syukur gw dow...
4  [bagus si sbnrnya cmn skrg suka kesel grgr sho...
5  [aplikasi yang sangat membantu, aplikasi bagus...
6                           [mantap, mantap, mantap]
7         [sangat bagus, sangat bagus, sangat bagus]
8  [bgus, bgus, skrg mb ny nambah besar yadi hape...
9                                       [ok, ok, ok]

In [8]:
# Mendapatkan info topik (Topic, Count, Name, Representation)
topic_info = topic_model.get_topic_info()
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,113,-1_aplikasi_di_saya_shopee,"[aplikasi, di, saya, shopee, ini, indonesia, t...",[online mall terbaik aqohhh sementara ini buat...
1,0,163,0_shopee_belanja_dan_mudah,"[shopee, belanja, dan, mudah, harga, banyak, s...","[puas belanja di shopee, shopee belanja lebih ..."
2,1,159,1_di_pengiriman_tidak_saya,"[di, pengiriman, tidak, saya, kurir, paket, ud...",[untuk shopeenya udah bagus menurutku tapi unt...
3,2,72,2_iklan_aplikasi_di_video,"[iklan, aplikasi, di, video, ganggu, saya, lai...",[iklan lu tuh ganggu anjing udah syukur gw dow...
4,3,54,3_ga_lama_sampe_di,"[ga, lama, sampe, di, krn, nya, bisa, udh, jel...",[bagus si sbnrnya cmn skrg suka kesel grgr sho...
5,4,51,4_aplikasi_bagus_belanja_sangat,"[aplikasi, bagus, belanja, sangat, membantu, y...","[aplikasi yang sangat membantu, aplikasi bagus..."
6,5,38,5_mantap_keluar_bgusssss_lee,"[mantap, keluar, bgusssss, lee, iku, lanjutkan...","[mantap, mantap, mantap]"
7,6,37,6_bagus_sangat_bermanfaat_baik,"[bagus, sangat, bermanfaat, baik, biasa, bergu...","[sangat bagus, sangat bagus, sangat bagus]"
8,7,33,7_bgus_nan_mb_bgt,"[bgus, nan, mb, bgt, lemot, baguus, hapesaya, ...","[bgus, bgus, skrg mb ny nambah besar yadi hape..."
9,8,28,8_ok_oke_okey_wort,"[ok, oke, okey, wort, okeh, lanjutt, bgt, mant...","[ok, ok, ok]"
10,9,25,9_cepat_tepat_fast_dan,"[cepat, tepat, fast, dan, respon, mudah, sesua...","[cepat dan tepat, pengiriman cepat, sangat bai..."
11,10,25,10_bagus_luck_smoga_bagusterpercaya,"[bagus, luck, smoga, bagusterpercaya, baguss, ...","[bagus, bagus, bagus]"
12,11,22,11_keren_hu_goooddd_wow,"[keren, hu, goooddd, wow, waw, sukakik, cakep,...","[keren, keren, keren]"
13,12,20,12_membantu_sangat_keadaan_spaylater,"[membantu, sangat, keadaan, spaylater, membant...","[sangat membantu, sangat membantu, sangat memb..."
14,13,20,13_bagus_⁰⁹_so_nice,"[bagus, ⁰⁹, so, nice, si, oke, good, aja, bara...","[bagus, bagus, bagus]"
15,14,20,14_terimakasih_harapan_atas_bagusssssssss,"[terimakasih, harapan, atas, bagusssssssss, gu...","[terimakasih, terimakasih atas pelayanan nya s..."
16,15,17,15_puas_memuaskan_selalu_penglman,"[puas, memuaskan, selalu, penglman, dipesan, p...","[puas, puas, puas]"
17,16,15,16_puas_sangat_memuaskan_𝔰𝔞𝔫𝔤𝔞𝔱,"[puas, sangat, memuaskan, 𝔰𝔞𝔫𝔤𝔞𝔱, pelayananya,...","[sangat puas, sangat puas, sangat puas]"
18,17,14,17_baik_baikbaik_ok_lumayan,"[baik, baikbaik, ok, lumayan, semuanya, cukup,...","[baik, baik, baik]"
19,18,12,18_good_job_mantap_,"[good, job, mantap, , , , , , , ]","[good, good, good]"
20,19,11,19_cod_ga_limit_bisa,"[cod, ga, limit, bisa, kalo, tapi, pdhl, dibuk...","[kenapa gak bisa cod, shopee tolong kasih nomo..."
21,20,11,20_online_belanja_lengkap_memakaimenggunakan,"[online, belanja, lengkap, memakaimenggunakan,...","[sangat membantu saya dalam belanja online, ba..."

In [9]:
# Simpan ke folder data proyekmu
topic_info.to_csv('/content/drive/My Drive/CSV/bertopic_results.csv', index=False)

print("✅ Informasi topik telah disimpan!")

✅ Informasi topik telah disimpan!

In [10]:
df['Topic'] = topics
df['Topic']

0       2
1       8
2       7
3      12
4       0
       ..
955    13
956     2
957     1
958     3
959    18
Name: Topic, Length: 960, dtype: int64

In [14]:
# Jika label 1 = Positif, 0 = Negatif
df['Sentiment_Label'] = df['label'].map({1: 'Positif 😊', 0: 'Negatif 😡'})
df['Sentiment_Label']

0      Negatif 😡
1      Positif 😊
2      Negatif 😡
3      Negatif 😡
4      Positif 😊
         ...
955    Positif 😊
956    Negatif 😡
957    Negatif 😡
958    Positif 😊
959    Positif 😊
Name: Sentiment_Label, Length: 960, dtype: object

In [15]:
#filter topik -1 (outlier) agar fokus
df_filtered = df[df['Topic'] != -1]

In [16]:
# 3. Buat pivot table: Baris = Topik, Kolom = Sentimen
sentiment_per_topic = df_filtered.groupby(['Topic', 'Sentiment_Label']).size().unstack(fill_value=0)

# 4. Ambil nama asli topiknya (bukan cuma angka)
topic_names = topic_model.get_topic_info()[['Topic', 'Name']]
sentiment_per_topic = sentiment_per_topic.merge(topic_names, on='Topic')

In [18]:
print(sentiment_per_topic.columns)

Index(['Topic', 'Negatif 😡', 'Positif 😊', 'Name'], dtype='object')

In [20]:
# Simpan ke folder data proyekmu
sentiment_per_topic.to_csv('/content/drive/My Drive/CSV/shopee_sentiment_per_topic.csv', index=False)

print("✅ Informasi topik telah disimpan!")

✅ Informasi topik telah disimpan!